### PR TITLE
Init Go project

### PR DESCRIPTION
**Pull request by ankithans**
#5  Placeholder commands
```
$ go install charmil

$ charmil install
install called

$ charmil list
list called

$ charmil remove
remove called

$ charmil --help
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  charmil [command]

Available Commands:
  help        Help about any command
  install     A brief description of your command
  installed   A brief description of your command
  list        A brief description of your command
  remove      A brief description of your command

Flags:
      --config string   config file (default is $HOME/.charmil.yaml)
  -h, --help            help for charmil
  -t, --toggle          Help message for toggle

Use "charmil [command] --help" for more information about a command.
```

### CODE REVIEW

**Comment by wtrocki** [comment]
Why we need charmil CLI? What this CLI will do?

**Comment by ankithans** [comment]
I thought it will be managing all the extensions in the hostCLI

**Comment by wtrocki** [comment]
This needs rebase. Also I would cleanup commands etc. 

We do not build CLI. We build framework for other CLI's. 
Having charmil CLI will be confusing unless we document it's intentions

**Comment by wtrocki** [comment]
So idea is that someone will import our commands to their CLI and get all extensions out of the box. We might need example host CLI in our repository anyway. Also this CLI might also do other registry work in future.

This needs more work

**Comment by ankithans** [comment]
Okay, got it! Cleaning up

**Comment by wtrocki** [comment]
After some thoughts charmil CLI is good name for playing with the sample registry etc. for demo purposes, but we need to architecture our repository in a way that this CLI will be just example to not confuse people.

**Comment by wtrocki** [comment]
Let's get some useful changes from this PR and create new one. There is tons of unneeded commits and merge branches etc.

**Comment by ankithans** [comment]
okayy 👍👍

**Pull request closed without merging**
