### PR TITLE
chore: starter template for the cli without charmil

### PR DESCRIPTION
**Pull request by wtrocki**
This PR introduces starter plugin CLI codebase.
Codebase contains number of elements duplicated with core charmil - factory that we can move to charmil SDK once all those concepts are there. 

Creating for early feedback. This is not going to get merged due to number of problems:
- go submodule is not working
- cli name is hardcoded and not easy to change
- root command is hardcoded 
- Multiple elements in the PR needs to be pulled to SDK.
- This clashes with current examples
- Missing documentation and usage docs - requires more work - See #143 

 ## Verification

```
cd starter
make install
starter 
```

### CODE REVIEW

**Comment by wtrocki** [comment]
Idea - Starter might be separate repository (this will require us to do frequent releases so IMHO we can merge that now into charmil and get it moved if needed.

**Comment by wtrocki** [comment]
We might change cli name to be something like smpl or other non english world for simple search replace.

**Comment by wtrocki** [comment]
Looking for someone picking up this to integrate with charmil commands

**Comment by ankithans** [comment]
Like `charmil init CLI_NAME` can create a full fledged starter project, using predefined starter template
I want to take it over. want to work with go templates from a long time

**Comment by wtrocki** [comment]
but for that we need yet another thing: charmil cli to manage CLI to build CLIs :)

**Comment by ankithans** [comment]
okay, user can run `make setup` after cloning etc.. CLI can make this more easier just go get charmil and init. We can go for any as per suggestions.
I am creating issues, which needs to be done before this

**Comment by jackdelahunt** [comment]
Looks nice and is a good place to start. Just have a few questions/comments.

- Moving to a separate repo and changing name make sense with this for reasons said before and cloning the repo of the SDK to get the SDK seems weird
- Using a make command along the lines of `make charmil/init NAME=smpl` in this smpl repo sounds like a really nice feature as I don't think a separate CLI is necessary here
- @wtrocki can you just explain what do you mean by integrating this with charmil commands as I can't see what this looks like right now
- Creating a separate repo for this and start to add charmil to it as we go/add features makes sense instead of doing that all at once

**Comment by ankithans** [comment]
> @wtrocki can you just explain what do you mean by integrating this with charmil commands as I can't see what this looks like right now

https://github.com/spf13/cobra/tree/master/cobra
i think have a look at cobra cmd tool. It has utilities such as cobra init, cobra add cmd, etc. which comes with cobra's recommended settings with viper and all. Here we do have similar thing, we want the user to follow the charmil SDK and for easing this process, CLI tool is better(will rm the need for separate repo). But makefile will do the similar thing

**Comment by wtrocki** [comment]
> https://github.com/spf13/cobra/tree/master/cobra

Actually good point. Since I'm going to PTO soon let's have final call what we do with this:

1. Do we need separate repository for this now and move this source code?

2. Do we merge that without review and refine it on main later on to swap with charmil SDK?

**Comment by jackdelahunt** [comment]
> https://github.com/spf13/cobra/tree/master/cobra

Ah okay I thought they would have to clone our whole repo but this looks really cool and would be a really nice feature for poeple to use.

**Comment by wtrocki** [comment]
Cool. Enjoy playing with this!

**Pull request merged**
