### PR TITLE
feat: check for updates in starter

### LINKED ISSUE #138: Add check for updates feature that uses github releases

### PR DESCRIPTION
**Pull request by ankithans**
Closes #138 

### Description
- In Starter template https://github.com/aerogear/charmil-starter/pull/5
- Check for updates in starter

confusion in (devel); while doing 
```go
if info, ok := debug.ReadBuildInfo(); ok {
	fmt.Println(info.Main.Version) // it prints (devel)
}
```

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by wtrocki** [comment]
Why we are doing this particular problem?

**Comment by ankithans** [comment]
This is to prompt the user, if any update is available.

Screenshot 2021-08-05 at 5 02 38 PM

**Comment by wtrocki** [comment]
I get that - but why this is priority :D

**Comment by wtrocki** [comment]
Anyway.. let's get that over since it is done and move to more interesting things

**Pull request merged**
