### PR TITLE
Punctuation rule

### LINKED ISSUE #168: Punctuation rule in Charmil validator
As mentioned in https://github.com/redhat-developer/app-services-cli/issues/830, we can provide punctuation rule in validator. This issue is specific to full stops in flags description. But there can be multiple things like this. So let's grab the things we would like in punctuation rule.

### PR DESCRIPTION
**Pull request by ankithans**
Closes #168 

### Description

Add Punctuation Rule which checks the full stops in flags usage. 
other punctuation things should be added in this rule.

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation change

### Checklist

- [x] Documentation added for the feature
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
Rebase needed.

**Comment by wtrocki** [comment]
Let's release after merging this PR.

**Comment by wtrocki** [comment]
@ankithans looks like I have broken something. Merging and going to fix on main

**Comment by ankithans** [comment]
main module (github.com/aerogear/charmil) does not contain package github.com/aerogear/charmil/validator/v1/rules

while testing the validator module.. as it is a seperate module now.

**Pull request closed without merging**
