### PR TITLE
chore: remove starter from main

### PR DESCRIPTION
**Pull request by ankithans**
remove starter from main. No need to maintain the starter at 2 locations - in main and in separate repo [here](https://github.com/ankithans/charmil-starter-template)

### CODE REVIEW

**Comment by wtrocki** [comment]
but we do not have second location :)
You mean your experiment in your own org?

**Review by wtrocki — CHANGES_REQUESTED** [review]
Let me check why we do it tommorow

**Comment by ankithans** [comment]
yep sure! we can move it under aerogear or any other solution..

**Comment by wtrocki** [comment]
I do not think we should remove starter for now only because we will lose ability to work with unreleased changes of the core, validator etc. Separate repository will be painful to work with. 

We can always create separate repo for this no problem. Trick is that we do not have much content and there is no reason for us to slow things down. If you worried about init not being able to clone/extract subfolder let's create separate repository that we can manually sync with the main on release - that would also be great way to separate main from released versions used for init. WDYT?

**Comment by ankithans** [comment]
> let's create separate repository that we can manually sync with the main on release - that would also be great way to separate main from released versions used for init. WDYT?

this looks great!

**Comment by wtrocki** [comment]
https://github.com/aerogear/charmil-starter/settings/access

**Pull request closed without merging**
