### PR TITLE
chore: make validator separate package

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
@aerogear/charmil

**Review by ankithans — APPROVED** [review]

**Comment by wtrocki** [comment]
Let's:

- release
- update rhoas cli imports
- verify if we get charmil cli in releases


@ankithans do you mind doing update in rhoas?

**Comment by ankithans** [comment]
yep can you review #182 before release?

**Comment by ankithans** [comment]
why this build is queued

**Pull request merged**
