### PR TITLE
Refactor core

### PR DESCRIPTION
**Pull request by ankithans**
### Description
Extract packages from starter and put them into charmil-core
Next Step would be to make a starter CLI able to run all these packages!
after that a starter template -> then CLI tool

I will provide documentation for all the packages, once i get them running in the example

### CODE REVIEW

**Comment by wtrocki** [comment]
@ankithans Starter have opiniated libraries from rhoas bringing them to core might be challenging.
It is way easier to figure out core/config etc. and swap it with what is there

https://github.com/aerogear/charmil/issues/149

**Comment by wtrocki** [comment]
I thino this PR has tons of good changed:

- Removes elements that are already in core
- Swaps some elements with charmil

I will leave others for now as this PR might be too large to deal with all at the same time.

**Review by wtrocki — APPROVED** [review]
Good to go after cleanup and rebase. 
World class job

**Comment by wtrocki** [comment]
@namit-chandwani we are missing only config

**Comment by ankithans** [comment]
> Removes elements that are already in core
Swaps some elements with charmil

yes it does these changes and next I will make these new features in core - running with starter example

**Comment by wtrocki** [comment]
I will keep core small, well tested, well documented. PRs to core should be small and targeted.

**Comment by wtrocki** [comment]
Good to go!

**Comment by ankithans** [comment]
so are you recommending to implement/test these additions to core in this PR? we can do that as well!

**Comment by wtrocki** [comment]
> so are you recommending to implement/test these additions to core in this PR? we can do that as well!
This may be better as we will not have any unused code in main. All things will be well tested and documented before adding to main.

No I recommend to minimize amount of untested code landing into core without issues/discussion. 
Example: Colours - I do not see it being particularly useful but that is just my opinion.

**Pull request merged**
